development:
  api_url: "https://my.talkpush.com/api/talkpush_services/campaigns/campaign_id/campaign_invitations"
  api_key: "dbed2ab32d1e9f1453d1a321480debca"
  api_secret: "a7281c8ff4ad9d0d78ae640d4c63b64c"
  campaign_id: 4
  email: "careersph@vxi.com"
  phone: "(+63) 917 777 5555"
